### PR TITLE
Use pkg-config to find packages

### PR DESCRIPTION
**Pull request by JPEWdev**
Package config should be used to find packages instead of manually
searching for headers. This makes cross-compiling easier, as well as
makes it possible to build a static binary (in particular, libarchive is
annoying to link statically without using pkg-config)

### CODE REVIEW

**Comment by llunak** [comment]
Looks ok to me in general, but the Cirrus check fails, do you have any idea why? It built fine without your change.

**Comment by JPEWdev** [comment]
> Looks ok to me in general, but the Cirrus check fails, do you have any idea why? It built fine without your change.

It looks like pkg-config can't find libarchive.pc.... I don't really know a lot about FreeBSD, but it appears that it can't find it for some reason. I'll going to try and boot a freebsd QEMU image to see if I can replicate it

**Comment by JPEWdev** [comment]
> Looks ok to me in general, but the Cirrus check fails, do you have any idea why? It built fine without your change.

`libarchive` was missing from the package list

**Comment by llunak** [comment]
Thank you.

**Pull request merged**
