### PR TITLE
try local recompile when local cpp invocation fails

### PR DESCRIPTION
**Pull request by lynxeye-dev**
Proposed fix for #414.

### CODE REVIEW

**Comment by rohieb** [comment]
Hmm. Travis failures seem to be unrelated to the patch?

**Comment by HenryMiller1** [comment]
Can you rebase this on top to the latest and force push?  That will re-run the travis build, and also run additional CI jobs that have been added since.

**Comment by HenryMiller1** [comment]
The code looks good, and I agree it looks like a CI issue, but I reflexively don't like to look at code until CI passes.

**Comment by lynxeye-dev** [comment]
I just pushed an update which fixes all the test fallout caused by the local recompile fallback.

**Pull request merged**
