### PR TITLE
Add a travis continuous integration configuration.

### LINKED ISSUE #195: Enable a ci system
As you might be able to tell from my last two issues, I've been playing with [travis-ci](https://travis-ci.org/) as a possible ci build system for icecc.  I discovered a reference to this elsewhere on github and I decided to try it.

At this point I'm convinced that I can make this work. It is time to check with the community on if this is a good idea. There may be some considerations I'm not aware of (either with ci in general, or travis-ci in particular). Does anyone have any objection or other consideration that needs to be discussed?

Unless someone objects I will work on implemented travis-ci next week. This means I will be disabling all tests that fail as a first step to get a green baseline. I will then write issues to get them fixed.

You can see my work in progress at  https://github.com/HenryMiller1/icecream/tree/travis-ci. Note that this is work in progress, there is obvious cleanup required before this can be merged.

### PR DESCRIPTION
**Pull request by rillian**
Describe the build for linux and macOS, and run the tests on linux. I find this very helpful for evaluating pull requests. Someone with commit access will have to sign in to https://travis-ci.org/ and add the repo for feedback to be available.

Closes #195

### CODE REVIEW

**Comment by rillian** [comment]
Sorry @HenryMiller1, I saw your issue and wrote this without realizing you'd done most of the work already. Looks like I just came up with the same thing you did on your work-in-progress branch.

I also added a mac build, since that's a fairly different environment where we're also using icecream for one of my projects. I wasn't able to get the tests running there. However, I think this is still worth merging.

**Comment by HenryMiller1** [comment]
Hmm.. I thought I had permissions to do sign into travis-ci.org and turn the build on, but it appears I do not.  

@krf, @coolo Do either of you have the ability to do this, or would you be willing to share those permissions?  I'm not clear how to figure out who the admins are who can do this.

**Comment by HenryMiller1** [comment]
Your file is much cleaner than mine, though I was waiting until the tests passed in linux/ubuntu/trusty - do the tests pass for you? (I notice you are using the default: ubuntu precise - I didn't get the build to work there but I didn't spend much time on it.)

**Comment by krf** [comment]
I'm not a 'Owner'. Owners are @coolo, @danimo, @llunak

**Comment by coolo** [comment]
just give me a list - I don't want to stand in the way

**Comment by HenryMiller1** [comment]
looks like me and @johnmiked15 are the most active committers recently. We are both good candidates for promotion to admin.

**Comment by HenryMiller1** [comment]
@rillian typically the workflow is to collapse (git rebase -i) all your changesets into one big commit and then push (git push -f)

**Comment by rillian** [comment]
> Your file is much cleaner than mine, though I was waiting until the tests passed in linux/ubuntu/trusty - do the tests pass for you?

Yes, the tests passed for me. See https://travis-ci.org/rillian/icecream/jobs/219859528

> typically the workflow is to collapse (git rebase -i) all your changesets into one big commit

Ok, I'll squash. Thanks for the review!

**Comment by HenryMiller1** [comment]
The tests that are failing in ubuntu trusty are skipped (not supported) on precise.  No reason not to accept your change, but I'll be adding a trusty build once I get that it working.

**Comment by rillian** [comment]
Ah, I missed that. Thanks for checking!

**Comment by rillian** [comment]
@coolo To enable this, the steps are something like this:

1. Visit https://travis-ci.org/
2. Sign in with your github account.
3. Allow access to the icecc project so it can install webhooks.
4. Click on your name in the upper right corner.
5. Select 'Accounts'.
6. Select the `icecc` project from the left navbar.
7. If necessary click 'sync account' and wait ~20 seconds.
8. Click the slider next to `icecream` to enable integration testing on the repo.

**Comment by rillian** [comment]
@coolo (or anyone else with admin access) to enable this, the steps are something like this:

1. Visit https://travis-ci.org/
2. Sign in with your github account.
3. Allow access to the icecc project so it can install webhooks.
4. Click on your name in the upper right corner.
5. Select 'Accounts'.
6. Select the `icecc` project from the left navbar.
7. If necessary click 'sync account' and wait ~20 seconds.
8. Click the slider next to `icecream` to enable integration testing on the repo.

**Comment by coolo** [comment]
I did that now (icemon was already synced on travis btw) - and invited the two as org admins

**Comment by rillian** [comment]
Thanks @coolo and @HenryMiller1!

**Comment by HenryMiller1** [comment]
thank you @rillian

**Pull request merged**
