### PR TITLE
fix typo in icecream manpage

### PR DESCRIPTION
**Pull request by mostynb**
"warning" isn't a supported value for the ICECC_DEBUG environment
variable, should be "warnings".

### CODE REVIEW

**Comment by llunak** [comment]
Hmm. I guess nobody has used this much, and since all the others are in singular, the proper value should be rather "warning". Could you change this to rather accept both "warning" and also "warnings" for backwards compatibility?

**Comment by mostynb** [comment]
Done.  Do you think it's worth updating the manpage to refer to "warnings" also?

**Comment by llunak** [comment]
The way I see it, since all the others are in singular, the one and only(tm) value should be "warning". The value "warnings" should never be mentioned anywhere (I find it confusing to have both of them listed), it should only be handled for backwards compatibility. Does that make sense?

(Or maybe indeed it should have been only the manpage that needed fixing, I didn't realize --help listed the plural name as well, I originally assumed the "warnings" in the strcmp() was a typo.)

**Comment by mostynb** [comment]
Updated the PR to drop user-visible mention of "warnings".

**Pull request merged**
