### PR TITLE
Fix missed inclusion of signal.h

### PR DESCRIPTION
**Pull request by jimklimov**

### CODE REVIEW

**Comment by coolo** [comment]
no reason for the configure check - we include signal.h in other places

**Comment by jimklimov** [comment]
I did not find any check for `signal()` in the `configure.ac`, but maybe I did not look too deeply :-)

If you wish, I can remove the line (do not see how it hurts though)... so far there were other non-portability showstoppers that precluded me building this in a Solarish environment with little effort ;(

**Comment by coolo** [comment]
remove everything but the include - signal.h is portable enough

**Comment by jimklimov** [comment]
Not sure I agree fully, but hey - it's your project ;)
Done.

**Pull request merged**
