### PR TITLE
Fix autogenerated environments if /bin/cc is clang

### PR DESCRIPTION
**Pull request by nabijaczleweli**
аnd a depessimisation

See commit message for reasoning

### CODE REVIEW

**Comment by nabijaczleweli** [comment]
I mean, the alternative would be a goto instead, I guess? But there weren't any gotos in C++ code, so I didn't want to add any. I wrapped it in parens for the express reason of silencing this warning

**Comment by coolo** [comment]
Your goal is to call the block twice, no? Make it a function?

**Comment by nabijaczleweli** [comment]
You're right, of course. Updated

**Comment by nabijaczleweli** [comment]
Bumping after a month. Is this missing something?

**Review by HenryMiller1 — APPROVED** [review]

**Comment by HenryMiller1** [comment]
The CI failures are concerning, but I don't understand what they mean.  Can you rebase this to the latest to see if it  works?

**Comment by nabijaczleweli** [comment]
rebased

**Comment by nabijaczleweli** [comment]
aaand it passes cleanly

**Pull request merged**
