### PR TITLE
icecc-test-env: Add environment test script

### PR DESCRIPTION
**Pull request by JPEWdev**
A helpful environment test script which can be used to find problems
with an environment before sending it over to a remote node

Signed-off-by: Joshua Watt <JPEWhacker@gmail.com>

### CODE REVIEW

**Comment by llunak** [comment]
Can you please add usage of this to tests/test.sh ? Function buildnativetest() looks like a good place.

**Comment by JPEWdev** [comment]
Yes, I wasn't sure exactly how to handle an automated test case. Is it OK for it stop the test to prompt for the sudo password, or should it use -f flag to use fakechroot + fakeroot?

**Comment by JPEWdev** [comment]
I realize the test script was already calling sudo, so its probably wasn't a concern that icecc-create-env also did so.

Done

**Comment by JPEWdev** [comment]
I tracked down the asan an lsan errors in Travis. The compilerwrapper is compiled with "-fsanitizer=..." from the exported CXXFLAGS, however the address sanitizer for clang appears to try and read /proc/self/maps, which doesn't exist in the chroot. This causes my test script to fail (in this build), and the build to fail later (in other builds). There doesn't appear to be any way to turn off the sanitizers at runtime, or at least you can't turn them off before it tries to access /proc/self/maps.

It only affects the toolchain when clang is used to compile compilerwrapper, and when TESTCC=clang (which causes compilerwrapper to be included in the environment).

I *think* the solution would be to add -fno-sanitize=all to the compile command line for compilerwrapper, but it would have to come *after* the user CXXFLAGS, which automake doesn't seem willing to do (or at least I don't know how to make automake do it).

**Comment by llunak** [comment]
The test script itself does not call sudo, it's the optional Makefile preparation. Calling test.sh alone should work fine even without sudo.

Can you make the usage in test.sh use sudo with -n? Something like (untested):

retcode=
sudo -n test-env $whatever
retcode=$?
if $retcode -eq 1; then
  if ! command -v fakeroot >/dev/null; then
    echo Cannot explicitly verify environment, use sudo or fakeroot.
    skipped_tests="$skipped_tests testenv"
  else
    test-env --fakeroot $whatever
    retcode=$?
  fi
fi
if test -n "$retcode" -a $retcode -ne 0; then
  # test failed
fi

**Comment by llunak** [comment]
As for compilerwrapper, a simple and reasonable solution would be not bother with it. It's for backwards compatibility with nodes that are several years old by now and if everything else works, presumably a simple wrapper will keep working as well.

If you want to compile it without ASAN, see services/Makefile.am , it sets per-target CXXFLAGS, that should work. In that case you'll need to add a configure check for whether the flag actually exists.

**Comment by JPEWdev** [comment]
The per-target CXXFLAGS are applied by automake before the user supplied CXXFLAGS environment variable, so that doesn't help unfortunately (I need to override the -fsanitize= options the user has provided). I think I'll take the easy route and not test the compiler wrapper in clang since they appear to be deprecated.

**Comment by llunak** [comment]
Ok. Thanks.

**Pull request merged**
