### PR TITLE
add -m <ver> flag to icecc-scheduler

### PR DESCRIPTION
**Pull request by mostynb**
This makes it possible to select the minimum supported protocol
version at icecc-scheduler startup time.  Useful for example if
you only want to allow daemons which support -gsplit-dwarf
the debugging option (protocol version 35).

This seems to work, but needs a bit more testing- my version of icemon can't connect when I set the minimum protocol version to 35 (I will try compiling that instead of using ubuntu's package).

### CODE REVIEW

**Comment by HenryMiller1** [comment]
Where are the tests?  I really do not like merging code changes that don't make an attempt at writing tests.

**Comment by HenryMiller1** [comment]
I think that we want to allow all icemon to use older protocol versions if it wants, or at least require icemon upgrades on a different scheme from clients.

**Comment by johnmiked15** [comment]
I think this change solves your original intent albeit much more simply:

https://gist.github.com/johnmiked15/d6daddcfb7abf78d2aee82402c28ebd5

**Comment by llunak** [comment]
Given that issue #150, that has lead to this, has been closed, I'm going to close this as well. If you think there's still something to be done, see issue #150.

**Pull request closed without merging**
