### PR TITLE
Discover scheduler should wait full timeout before selcting scheduler

### LINKED ISSUE #110: iceccd prefers scheduler on localhost, even if better scheduler is availble
Experimenting with running multiple schedulers with 1.1rc1, I discovered that on any machine that is running a scheduler locally, iceccd will never discover any other scheduler on the network.  The scheduler on localhost does see the other scheduler and disconnects everyone, but iceccd on that host will always reconnect to the local scheduler, not the better one on a different machine.  Daemons on machines on different networks seem to work correctly.

Running scheduler -vv I see the following in the log:
[20423] 16:01:35: ICECREAM scheduler 1.0.98 starting up, port 8765
[20424] 16:01:35: broadcast eth0 10.140.160.127
[20424] 16:01:35: broadcast from 10.140.160.34:58982 (version 34)
[20424] 16:01:35: broadcast from 10.140.160.34:58890 (version 34)
[20424] 16:01:35: broadcast from 10.140.160.34:57476 (version 29)
[20424] 16:02:11: Scheduler from 10.140.160.15:43476 (version 34) has announced itself as a preferred scheduler, disconnecting all connections.
[20424] 16:02:11: remove daemon [hostname removed]

and iceccd running -vv shows the following
[20436] 16:01:35: Suitable scheduler found at 10.140.160.34:8765 (version: 34)
[20436] 16:01:35: scheduler is on 10.140.160.34:8765 (net ICECREAM)
[20436] 16:01:35: scheduler not yet found.
[20436] 16:01:38: Connected to scheduler (I am known as 10.140.160.34)
[20436] 16:02:11: scheduler closed connection
[20436] 16:02:38: broadcast eth0 10.140.160.127
[20436] 16:02:38: scheduler not yet found.
[20436] 16:02:38: Suitable scheduler found at 10.140.160.34:8765 (version: 34)
[20436] 16:02:38: scheduler is on 10.140.160.34:8765 (net ICECREAM)
[20436] 16:02:38: scheduler not yet found.
[20436] 16:02:41: Connected to scheduler (I am known as 10.140.160.34)

I would suggest the scheduler not respond to broadcasts when it thinks there is a better scheduler, but still listen, if there is a timeout it should take over.

### PR DESCRIPTION
**Pull request by HenryMiller1**
This should fix #110 and #107, and replaces #111

### CODE REVIEW

**Comment by HenryMiller1** [comment]
Other than readme.md, the change is atomic.   Many of the changes are actually just whitespace - much existing code had to be wrapped in an if and that resulted in many changes just to get indentation correct.

If you disagree, I'll need some help in figuring out a way to atomically split this up.

**Comment by ossilator** [comment]
by "git gui" i mean - surprise surprise - "git gui". no kidding.

i can't judge whether that commit should to be split beyond this, but this just emphasizes that you need to be a tad more verbose, at least as far as i'm concerned. put the relevant information into the commit messages, not the pull request cover messages (which are just for context and will be virtually lost after merging).

you can get some inspiration from https://wiki.qt.io/Commit_Policy (point 8 in particular).

**Comment by HenryMiller1** [comment]
Are you requesting that I close this pull request and create a new one?  Or is there a way to fix this?

**Comment by ossilator** [comment]
i must admit that i don't know, as i don't interact much with github. under "normal git circumstances", a forced push of the cleaned up branch would fix the problem.

**Comment by coolo** [comment]
it does. the PR is basically only tracking the branch - so force push

**Comment by HenryMiller1** [comment]
Is this what you were looking for?

**Comment by diginc** [comment]
+1

**Pull request merged**
