### PR TITLE
Added preprocessing load control

### PR DESCRIPTION
**Pull request by derekgorcz**
It appears that the daemon already has process limiting logic in Daemon::handle_old_request() https://github.com/icecc/icecream/blob/master/daemon/main.cpp#L1250. The additional logic added to the client side will inform the daemon of a local build before it calls fork() for a local compile(the fork and exec is done via call_cpp()).

### CODE REVIEW

**Comment by HenryMiller1** [comment]
Are we handling the case where there is no local daemon running (crashed, or never started)?

**Comment by HenryMiller1** [comment]
I'm not sure if such a case exists as we are already in the remote build, but just checking.

**Comment by derekgorcz** [comment]
It seems that in build_remote() there is already some logic that is blindly dereferencing local_daemon. e.g. local_daemon->send_msg(getcs). In the case that sending fails we are throwing a client_error which is caught in client main function that will return immediately.

**Comment by derekgorcz** [comment]
Also, I believe that if you run the client without a daemon for it to connect to it will just throw and error and halt execution.

**Pull request merged**
